BucOverflow/Controllers/AnswerController.cs
using BucOverflow.Models;
using Microsoft.AspNetCore.Mvc;

namespace BucOverflow.Controllers
{
    public class AnswerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //saves a users answer to a question
        [HttpPost]
        public IActionResult AddAnswer(string answerText, int questionID)
        {
            using (var db = new DataContext())
            {
                //gets the last answer entry in the db
                var lastEntry = db.Answers
                      .OrderByDescending(x => x.AnswerID)
                      .FirstOrDefault();

                //news up answer model and assigns values
                AnswerModel answer = new AnswerModel();
                answer.AnswerText = answerText;
                answer.QuestionID = questionID;
                answer.AnswerID = lastEntry.AnswerID + 1;

                //saves new entry to db
                db.Add(answer);
                db.SaveChanges();

                //returns the user to the question page they were on
                return RedirectToAction("ViewQuestion", "Question", new { questionID = questionID });
            }//end using (var db = new DataContext())
        }//end public IActionResult Answer(string AnswerText, int QuestionID)
    }
}

BucOverflow/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using BucOverflow.Models;
using System.Diagnostics;
using System.Globalization;

namespace BucOverflow.Controllers
{
    public class QuestionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //Returns a question
        public IActionResult ViewQuestion(int questionID)
        {
            using (var db = new DataContext())
            {
                //pulls the current question from the db
                QuestionModel question = db.Questions.Find(questionID);

                //creates a list of answers for the given question
                List<AnswerModel> answers = new List<AnswerModel>();
                foreach (var a in db.Answers)
                {
                    if (a.QuestionID == question.QuestionID)
                    {
                        AnswerModel ans = a;
                        answers.Add(a);
                    }
                }

                ViewBag.answers = answers;

                return View("Question", question);
            }//end using (var db = new DataContext())
        }//public IActionResult ViewQuestion(int questionID)

        //returns the form for submitting a new question
        public IActionResult NewQuestion()
        {
            return View();
        }

        //handles the logic of posting a new question before returning user to the question list
        public IActionResult PostQuestion(QuestionModel question)
        {
            using (var db = new DataContext())
            {
                question.DateAsked = DateTime.Now.ToString("g", CultureInfo.GetCultureInfo("en-US"));
                db.Questions.Add(question);
                db.SaveChanges();
            }
            return RedirectToAction("QuestionList", "Forum");
        }
    }
}

BucOverflow/Views/Question/NewQuestion.cshtml
@model BucOverflow.Models.QuestionModel

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

<br />
<br />
<form method="post" action="@Url.Action("PostQuestion", "Question")">
    <div style="padding-inline: 5%">
        <div class="align-left">
            <h1 class="display-4">
                <label><strong>Question Title</strong></label>
                <h2><input type="text" name="Title" style="border: 1px solid darkgrey"/></h2>
            </h1>
        </div>
        <br />
        <br />
        <div style="width: 45rem; height: 30rem">
            <h4><strong>Explain your question in more detail:</strong></h4>
            <textarea name="UserText" style="border: 1px solid darkgrey; width:inherit; height:inherit; resize:none"></textarea>
            <br />
            <button class="btn btn-secondary" type="submit" style="float:right">Submit Question</button>
        </div>
    </div>
</form>
<br />
<br />
<br />
<br />

<script>
    $(document).ready(function () {
            $('form').submit(function () {
                var answerText = $('textarea[name="UserText"]').val();
                if ($.trim(answerText) === '') {
                    alert('Question body cannot be empty.');
                    return false;
                }
            });
    });
</script>

<script>
    $(document).ready(function () {
            $('form').submit(function () {
                var answerText = $('input[name="Title"]').val();
                if ($.trim(answerText) === '') {
                    alert('Question title cannot be empty.');
                    return false;
                }
            });
    });
</script>

BucOverflow/Views/Question/Question.cshtml
@model BucOverflow.Models.QuestionModel
@{
    List<AnswerModel> answers = ViewBag.answers;
    ViewData["Title"] = Model.Title;
    ViewData["QuestionBody"] = Model.UserText;
    ViewData["TimeAsked"] = Model.DateAsked;
    ViewData["AnsweringUser"] = "Test User";
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

<div style="padding-inline: 5%">
    <div class="align-left">
        <h1 class="display-4">
            <br /><strong>@ViewData["Title"]</strong>
        </h1>
    </div>

    <div class="align-left">
        <p>
            Asked: @ViewData["TimeAsked"]
        </p>
    </div>

    <div style="border: 1px solid darkgrey">
        <p style="padding: 1%;">
            @ViewData["QuestionBody"]
        </p>
    </div>
    <br />
    <form method="post" action="@Url.Action("AddAnswer", "Answer")">
        <div>
            <br />
            @Html.HiddenFor(model => model.QuestionID)
            <div>
                <strong><label><h4>Post a reply</h4></label></strong>
                <div style="padding-block: 1%">
                    <textarea style="resize: none;" name="AnswerText" rows="8" cols="50"></textarea>
                </div>
                <button class="btn btn-secondary" type="submit">Post Answer</button>
            </div>
    </form>
    <br />
    <br />
    <h3>Answers</h3>
    <br />
    @{
        if (answers.Count == 0)
        {
            <div>
                <p style="padding: 1%;">
                    <h4>There are no answers at this time.</h4>
                </p>
            </div>
            <br />
            <div />
            <br />
        }
        else
        {
            foreach (var a in answers)
            {
                <div style="border: 1px solid darkgrey;">
                    <label style="padding: 1%">
                        <strong style="padding-bottom: 15px; border-bottom-style: solid; border-bottom-width: 3.1px; width: fit-content;">@ViewData["AnsweringUser"]</strong>
                    </label>
                    <p style="padding: 1%;">
                        @Html.Raw(a.AnswerText)
                    </p>
                </div>
                <br />
                <div />
            }
        }
    }

    <script>
        $(document).ready(function () {
            $('form').submit(function () {
                var answerText = $('textarea[name="AnswerText"]').val();
                if ($.trim(answerText) === '') {
                    alert('Answer cannot be empty.');
                    return false;
                }
            });
        });
    </script>